In [2]:
# TENSORFLOW

import tensorflow as tf
import numpy as np

In [3]:
a=tf.constant(15)
b=tf.constant(20)

In [4]:
print(a*b)

tf.Tensor(300, shape=(), dtype=int32)


In [5]:
x=np.random.rand(100).astype(np.float32)

In [6]:
print(x)

[0.68182516 0.87208617 0.18774691 0.46451288 0.12848239 0.14692128
 0.87079114 0.33628005 0.46046335 0.42625296 0.20148166 0.03660452
 0.9506295  0.76418465 0.21761043 0.37999398 0.958878   0.512555
 0.38596722 0.47536388 0.4282201  0.863452   0.06946731 0.05002882
 0.900889   0.34457204 0.7763436  0.13641782 0.6819881  0.4240547
 0.758475   0.92565686 0.71833956 0.5602366  0.7780821  0.07972595
 0.6506808  0.96289665 0.11268034 0.24725424 0.3764271  0.5344097
 0.8528146  0.13895655 0.01483641 0.94988155 0.87403136 0.05390132
 0.17694795 0.15313563 0.89042217 0.69967604 0.85795504 0.5193077
 0.35250866 0.6258471  0.00971831 0.05341048 0.951322   0.9879326
 0.97065353 0.26298726 0.33923608 0.57778305 0.28973827 0.49859354
 0.6471938  0.9651912  0.3037276  0.65699685 0.42151016 0.5098297
 0.9101609  0.5169067  0.78244114 0.4661661  0.837714   0.76351625
 0.49749002 0.46045384 0.46561036 0.5567472  0.16684115 0.15136345
 0.5096241  0.7416573  0.02342471 0.3304677  0.30571595 0.36932623
 0

In [7]:
y=0.2*x+0.2

In [8]:
W=tf.Variable(tf.random.normal([1]))

In [9]:
b=tf.Variable(tf.zeros([1]))

In [10]:
def mse_loss():
    y_pred=W*x+b
    loss=tf.reduce_mean(tf.square(y_pred-y))
    return loss

In [11]:
optimizer=tf.optimizers.Adam()

In [12]:
for step in range(5000):
    optimizer.minimize(mse_loss, var_list=[W,b])
    if step%500==0:
        print(step, W.numpy(),b.numpy())

0 [0.01791271] [0.00099999]
500 [0.20770347] [0.19451842]
1000 [0.2043059] [0.19764437]
1500 [0.20153916] [0.19915797]
2000 [0.20036723] [0.1997991]
2500 [0.20005311] [0.19997096]
3000 [0.20000449] [0.19999751]
3500 [0.20000125] [0.19999929]
4000 [0.20000099] [0.19999944]
4500 [0.20000073] [0.19999959]


In [1]:
# PYTORCH


import torch
import numpy as np

In [2]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [5]:
print(type(x_np))

<class 'torch.Tensor'>


In [6]:
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)

One Tensor: 
 tensor([[1, 1],
        [1, 1]])


In [7]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

tensor([[0.3000, 0.5007],
        [0.1355, 0.4006]])


In [14]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))

tensor([[0.2523, 0.5673, 0.6331],
        [0.0081, 0.8180, 0.0407]])
<class 'torch.Tensor'>


In [15]:
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>


In [16]:
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [17]:
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[0.4187, 0.8991, 0.0667, 0.9219],
        [0.0131, 0.4059, 0.2474, 0.7652],
        [0.7810, 0.3223, 0.3388, 0.7220]])


device(type='cpu')

In [19]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("Device tensor is stored in ", tensor.device)

In [21]:
tensor = torch.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [22]:
tensor1 = torch.zeros(4,4)
print(tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [23]:
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [24]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
tensor.add_(3)
print(tensor)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [26]:
t = torch.ones(5)
print(t)

tensor([1., 1., 1., 1., 1.])


In [27]:
n = t.numpy()
print(n)
print(type(n))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
